# Generated by Django 3.2.15 on 2022-09-27 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Id_Categoria', models.AutoField(primary_key=True, serialize=False)),
                ('Categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Ingresado',
            fields=[
                ('Id_ProductoIngresado', models.AutoField(primary_key=True, serialize=False)),
                ('Producto', models.CharField(max_length=50, null=True)),
                ('Valor', models.DecimalField(decimal_places=0, default=0.0, max_digits=8)),
                ('Color', models.CharField(max_length=50)),
                ('Tipo_Material', models.CharField(max_length=50)),
                ('Fecha_Ingreso', models.DateTimeField(auto_now_add=True)),
                ('URL', models.URLField()),
                ('Id_Categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.categoria')),
                ('Id_Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.proveedor')),
            ],
        ),
    ]
